name: Build and push packages

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: 'flowfuse/github-actions-workflows/.github/workflows/build_node_package.yml@v0.34.0'
    with:
      node: '[
              {"version": "16", "tests": true, "lint": false},
              {"version": "18", "tests": true, "lint": true},
              {"version": "20", "tests": true, "lint": true},
            ]'

  publish:
    needs: build
    if: |
      ( github.event_name == 'push' && github.ref == 'refs/heads/main' ) ||
      ( github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main' )
    uses: 'flowfuse/github-actions-workflows/.github/workflows/publish_node_package.yml@v0.34.0'
    with:
      package_name: nr-assistant
      publish_package: true
    secrets:
      npm_registry_token: ${{ secrets.NPM_PUBLISH_TOKEN }}

  dispatch_nr_launcher:
    name: Dispatch nr-launcher package build
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.GH_BOT_APP_ID }}
          private_key: ${{ secrets.GH_BOT_APP_KEY }}
      - name: Trigger nr-launcher package build
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: publish.yml
          repo: flowfuse/nr-launcher
          ref: main
          token: ${{ steps.generate_token.outputs.token }}
